import mongoose from "mongoose";

const userSchema = new mongoose.Schema(
  {
    userName: {
      type: String,
      required: true,
      unique: true,
    },
    email: {
      type: String,
      required: true,
      unique: true,
    },
    password: {
      type: String,
      required: true,
    },
    firstName: {
      type: String,
      required: true,
    },
    lastName: {
      type: String,
      required: true,
    },
    gender: {
      type: String,
      required: true,
      enum: ["male", "female"],
    },
    profilePic: {
      type: String,
      default: "",
      required: true,
    },
    age: {
      type: Number,
      required: true,
    },
    bio: {
      type: String,
      default: "",
    },
    mobile_no: {
      type: Number,
      required: true,
      unique: true,
    },
    dob: {
      type: String,
      required: true,
    },
    religion: {
      type: String,
      required: true,
      enum: [
        "hindu",
        "muslim",
        "christian",
        "sikh",
        "jain",
        "buddhist",
      ],
    },
    maritalStatus: {
      type: String,
      required: true,
      enum: ["single", "married", "divorced", "widowed"],
    },
    motherTongue: {
      type: String,
      required: true,
      enum: [
        "hindi",
        "english",
        "punjabi",
        "bengali",
        "tamil",
        "telugu",
        "marathi",
        "urdu",
        "kannada",
        "gujarati",
        "odisha",
        "malayalam",
      ],
    },
    nationality: {
      type: String,
      required: true,
      enum: [
        "indian",
        "american",
        "british",
        "australian",
        "canadian",
      ],
    },
    education: {
      type: String,
      required: true,
      enum: [
        "10th",
        "12th",
        "diploma",
        "graduation",
        "post-graduation",
        "doctorate",
      ],
    },
    occupation: {
      type: String,
      required: true,
      enum: [
        "student",
        "business",
        "job",
        "self-employed",
        "not-working",
      ],
    },
    income: {
      type: String,
      required: true,
      enum: [
        "0-2.5L",
        "2.5-5L",
        "5-7.5L",
        "7.5-10L",
        "10-15L",
        "15-20L",
        "20-30L",
        "30-50L",
        "50L+",
      ],
    },
    city: {
      type: String,
      required: true,
      enum: ["surat", "vadodara", "rajkot", "bhavnagar", "jamnagar"],
    },
    state: {
      type: String,
      required: true,
      enum: [
        "gujarat",
        "punjab",
        "haryana",
        "delhi",
        "maharashtra",
        "karnataka",
        "tamil Nadu",
      ],
    },
    country: {
      type: String,
      required: true,
      enum: [
        "india",
        "united States",
        "united Kingdom",
        "australia",
        "canada",
      ],
    },
    height: {
      type: String,
      required: true,
      enum: [
        "4'5",
        "4'6",
        "4'7",
        "4'8",
        "4'9",
        "4'10",
        "4'11",
        "5'0",
        "5'1",
        "5'2",
        "5'3",
        "5'4",
        "5'5",
        "5'6",
        "5'7",
        "5'8",
        "5'9",
        "5'10",
        "5'11",
        "6'0",
        "6'1",
        "6'2",
        "6'3",
        "6'4",
        "6'5",
        "6'6",
        "6'7",
        "6'8",
        "6'9",
        "6'10",
        "6'11",
        "7'0",
      ],
    },
    weight: {
      type: String,
      required: true,
      enum: [
        "40-45",
        "45-50",
        "50-55",
        "55-60",
        "60-65",
        "65-70",
        "70-75",
        "75-80",
        "80-85",
        "85-90",
        "90-95",
        "95-100",
        "100+",
      ],
    },
    hobbies: {
      type: String,
      required: true,
      enum: [
        "reading",
        "writing",
        "painting",
        "singing",
        "dancing",
        "cooking",
        "travelling",
        "photography",
        "gardening",
      ],
    },
    you_live_with_family: {
      type: Boolean,
      default: false,
      required: true,
    },
    diet: {
      type: String,
      required: true,
      enum: ["vegetarian", "non-vegetarian", "eggetarian", "vegan"],
    },
    likedProfile: {
      type: Array,
      default: [],
    },
    matchedProfile: {
      type: Array,
      default: [],
    },
    myPhotos: {
      type: Array,
      default: [],
    },
  },
  { timestamps: true }
);

const User = mongoose.model("User", userSchema);
export default User;
